# Generated by Django 3.2 on 2022-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='人物名字')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComicsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='漫画名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreatorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='创作者名字')),
                ('role', models.CharField(max_length=255, verbose_name='角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='事件标题')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(verbose_name='图片链接')),
                ('extension', models.CharField(max_length=255, verbose_name='图片拓展名')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicWebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='公共网站详情链接')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='系列标题')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='故事标题')),
                ('type', models.CharField(max_length=255, verbose_name='类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unique_id', models.IntegerField(db_index=True, verbose_name='漫威ID')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='漫威修改时间')),
                ('thumbnail', models.URLField(verbose_name='缩略图链接')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('title', models.CharField(max_length=255, verbose_name='故事标题')),
                ('type', models.CharField(max_length=255, verbose_name='故事类型')),
                ('character', models.ManyToManyField(to='marvel.CharacterItem', verbose_name='角色')),
                ('comics', models.ManyToManyField(to='marvel.ComicsItem', verbose_name='漫画')),
                ('creator', models.ManyToManyField(to='marvel.CreatorItem', verbose_name='创作者')),
                ('event', models.ManyToManyField(to='marvel.EventItem', verbose_name='事件')),
                ('original_issue', models.ManyToManyField(to='marvel.OriginalIssue', verbose_name='故事原因')),
                ('series', models.ManyToManyField(to='marvel.SeriesItem', verbose_name='系列')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unique_id', models.IntegerField(db_index=True, verbose_name='漫威ID')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='漫威修改时间')),
                ('thumbnail', models.URLField(verbose_name='缩略图链接')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('title', models.CharField(max_length=255, verbose_name='系列名称')),
                ('rating', models.CharField(max_length=255, verbose_name='年龄适用等级')),
                ('character', models.ManyToManyField(to='marvel.CharacterItem', verbose_name='角色')),
                ('comics', models.ManyToManyField(to='marvel.ComicsItem', verbose_name='漫画')),
                ('creator', models.ManyToManyField(to='marvel.CreatorItem', verbose_name='创作者')),
                ('event', models.ManyToManyField(to='marvel.EventItem', verbose_name='事件')),
                ('story', models.ManyToManyField(to='marvel.StoryItem', verbose_name='故事')),
                ('url', models.ManyToManyField(to='marvel.PublicWebSite', verbose_name='公共网站详情链接')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unique_id', models.IntegerField(db_index=True, verbose_name='漫威ID')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='漫威修改时间')),
                ('thumbnail', models.URLField(verbose_name='缩略图链接')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('title', models.CharField(max_length=255, verbose_name='事件标题')),
                ('character', models.ManyToManyField(to='marvel.CharacterItem', verbose_name='角色')),
                ('comics', models.ManyToManyField(to='marvel.ComicsItem', verbose_name='漫画')),
                ('creator', models.ManyToManyField(to='marvel.CreatorItem', verbose_name='创作者')),
                ('series', models.ManyToManyField(to='marvel.SeriesItem', verbose_name='系列')),
                ('story', models.ManyToManyField(to='marvel.StoryItem', verbose_name='故事')),
                ('url', models.ManyToManyField(to='marvel.PublicWebSite', verbose_name='公共网站详情链接')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unique_id', models.IntegerField(db_index=True, verbose_name='漫威ID')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='漫威修改时间')),
                ('thumbnail', models.URLField(verbose_name='缩略图链接')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('full_name', models.CharField(max_length=255, verbose_name='全名')),
                ('suffix', models.CharField(max_length=255, verbose_name='荣誉')),
                ('comics', models.ManyToManyField(to='marvel.ComicsItem', verbose_name='漫画')),
                ('event', models.ManyToManyField(to='marvel.EventItem', verbose_name='事件')),
                ('series', models.ManyToManyField(to='marvel.SeriesItem', verbose_name='系列')),
                ('story', models.ManyToManyField(to='marvel.StoryItem', verbose_name='故事')),
                ('url', models.ManyToManyField(to='marvel.PublicWebSite', verbose_name='公共网站详情链接')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unique_id', models.IntegerField(db_index=True, verbose_name='漫威ID')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='漫威修改时间')),
                ('thumbnail', models.URLField(verbose_name='缩略图链接')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('title', models.CharField(max_length=255, verbose_name='漫画名称')),
                ('description_text', models.TextField(verbose_name='漫画文本描述')),
                ('character', models.ManyToManyField(to='marvel.CharacterItem', verbose_name='角色')),
                ('creator', models.ManyToManyField(to='marvel.CreatorItem', verbose_name='创作者')),
                ('event', models.ManyToManyField(to='marvel.EventItem', verbose_name='事件')),
                ('image', models.ManyToManyField(to='marvel.Image', verbose_name='图片')),
                ('series', models.ManyToManyField(to='marvel.SeriesItem', verbose_name='系列')),
                ('story', models.ManyToManyField(to='marvel.StoryItem', verbose_name='故事')),
                ('url', models.ManyToManyField(to='marvel.PublicWebSite', verbose_name='公共网站详情链接')),
                ('variant', models.ManyToManyField(to='marvel.Variant', verbose_name='问题')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('unique_id', models.IntegerField(db_index=True, verbose_name='漫威ID')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='漫威修改时间')),
                ('thumbnail', models.URLField(verbose_name='缩略图链接')),
                ('resource_uri', models.URLField(verbose_name='资源链接')),
                ('name', models.CharField(max_length=20, verbose_name='角色名字')),
                ('comics', models.ManyToManyField(to='marvel.ComicsItem', verbose_name='漫画')),
                ('event', models.ManyToManyField(to='marvel.EventItem', verbose_name='事件')),
                ('series', models.ManyToManyField(to='marvel.SeriesItem', verbose_name='系列')),
                ('story', models.ManyToManyField(to='marvel.StoryItem', verbose_name='故事')),
                ('url', models.ManyToManyField(to='marvel.PublicWebSite', verbose_name='公共网站详情链接')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
