# Generated by Django 3.2 on 2022-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveIntegerField(choices=[(2, '展示'), (1, '隐藏'), (0, '删除')], default=1, verbose_name='状态')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='数值越大越靠前', verbose_name='优先级')),
                ('name', models.CharField(max_length=15, verbose_name='分类')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveIntegerField(choices=[(2, '展示'), (1, '隐藏'), (0, '删除')], default=1, verbose_name='状态')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='数值越大越靠前', verbose_name='优先级')),
                ('name', models.CharField(max_length=15, verbose_name='标签')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveIntegerField(choices=[(2, '展示'), (1, '隐藏'), (0, '删除')], default=1, verbose_name='状态')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='数值越大越靠前', verbose_name='优先级')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('view', models.PositiveIntegerField(default=0, editable=False, verbose_name='阅读数')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('like', models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数')),
                ('collect', models.PositiveIntegerField(default=0, editable=False, verbose_name='收藏数')),
                ('category', models.ForeignKey(on_delete=models.SET(''), to='blog.category', verbose_name='分类')),
                ('tag', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
