# Generated by Django 3.2 on 2022-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveIntegerField(choices=[(2, '展示'), (1, '隐藏'), (0, '删除')], default=1, verbose_name='状态')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='数值越大越靠前', verbose_name='优先级')),
                ('name', models.CharField(max_length=15, verbose_name='标题')),
                ('url', models.URLField()),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveIntegerField(choices=[(2, '展示'), (1, '隐藏'), (0, '删除')], default=1, verbose_name='状态')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='数值越大越靠前', verbose_name='优先级')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('display_type', models.PositiveIntegerField(choices=[(1, '最新文章'), (2, '最热文章'), (3, '评论最多'), (4, '收藏最多'), (5, '点赞最多'), (6, '阅读数最多')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, max_length=200, verbose_name='内容')),
                ('position', models.BooleanField(choices=[(True, '左边'), (False, '右边')], default=False, verbose_name='位置')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
