# Generated by Django 3.1 on 2020-09-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_comment_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
