# Generated by Django 2.2.13 on 2020-07-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('navigation', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.Category')),
                ('tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tag.Tag')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
